application/tables/__init__.py
from flask import Blueprint

tables_bp = Blueprint('tables', __name__, template_folder='templates',static_folder='static')

from application.tables import routes

application/tables/routes.py
from application.tables import tables_bp
from application import db
from application import db_models as mdl
from application.datetime_handler import now_utc
from application.tables import search, loader
from application.tables.paginate import paginate
from flask_login import login_required, current_user
from flask import request, abort, jsonify, session, render_template, flash, redirect, url_for
from sqlalchemy import text, func, literal_column
from sqlalchemy.exc import DataError
from sqlalchemy.orm import aliased, load_only
import json

@tables_bp.route('/component-table')
def component_table():
    all_components = [comp.serial_number for comp in mdl.Component.query]
    return render_template('component_table.html', title='Component Inventory', db_tablename='component', all_components=all_components)

@tables_bp.route('/module-table')
def module_table():    
    all_modules = [mod.serial_number for mod in mdl.Module.query]
    return render_template('module_table.html', title='Module Table', db_tablename='module', all_modules=all_modules, default_search='')

@tables_bp.route('/<constr_table>')
def construction_table(constr_table):
    return render_template('construction_table.html',title=f'{constr_table} Table'.capitalize(), constr_table=constr_table)

@tables_bp.route('/shipment-table/')
def shipment_table():
    return render_template('shipment_table.html', title='Shipment Table', db_tablename='shipment')


@tables_bp.route('/api/table_data/<db_tablename>')
def table_data(db_tablename):
    # Ref: https://blog.miguelgrinberg.com/post/beautiful-flask-tables-part-2
    Table = mdl.get_model_by_tablename(db_tablename)
    if db_tablename not in search.builder_map:
        flash('This table does not exists returning home', category='danger')
        return redirect(url_for('main.home'))
    
    query_director = search.QueryDirector(request.args.get('search'))
    query_builder = search.builder_map[db_tablename]()
    query_director.builder = query_builder 
    # these next 2 lines let people query by deprecation, overrides the default to filter by deprecated!
    if not any(search_key.lower() in search.DEPRECATION_QUERY_ALIASES for search_key, _ in query_director.grouped_searches):
        query_builder.query_deprecation(['False'], '=')
    query = query_director.build_query()

    #Store the raw SQL Query in the session, higher performance and space than storing ids
    session['table_query'] = str(query.compile(db.engine, compile_kwargs={"literal_binds": True}))
    starting_offset = request.args.get('start', type=int, default=-1) #-1 is for no query str params
    page_length = request.args.get('length', type=int, default=-1)

    if 'available_pages' not in session:
        session['available_pages'] = []
    
    try:
        ONE = literal_column("1")
        total_rows = db.session.execute(
            db.select(func.count(ONE)).select_from(query.subquery()).order_by(None)
        ).scalar_one()
        requested_rows, available_pages = paginate(Table, query, starting_offset, page_length, total_rows, session['available_pages'])
    except DataError:
        total_rows = 0
        requested_rows, available_pages = [], []
    session['available_pages'] = [page.model_dump() for page in available_pages]

    return {
        'data': loader.table_data(db_tablename, requested_rows),
        'total': total_rows,
    }

@tables_bp.route('/api/table_data/<db_tablename>', methods=['POST'])
@login_required
def update(db_tablename):
    data = request.get_json()
    if db_tablename == 'component':
        if 'id' not in data:
            abort(400)
        component = mdl.Component.get_by_id(data['id'])
        required_keys = component.component_type.required_keys
        try:
            meta_data = json.loads(data['meta_data'])
        except json.decoder.JSONDecodeError:
            return jsonify(message=f"Incorrect formatting for meta data ({data['meta_data']}), should be JSON formatted"), 400
        if set(required_keys) != set(meta_data.keys()):
            #there is the case where required keys changes for a component type after upload... but forcing it to conform to that is ok
            #abort(400, {'message': f'Cannot set metadata to be: {meta_data}, the allowed keys are: {set(required_keys)}'})
            return jsonify(message=f'Cannot set metadata to be: {meta_data}, the allowed keys are: {set(required_keys)}'), 400
        component.meta_data = meta_data
        db.session.commit()
    return '', 204

@tables_bp.route('/api/table_data/<db_tablename>/depricate', methods=['POST'])
@login_required
def depricate(db_tablename):
    query = session.get('table_query')
    if query is None:
        return jsonify(message=f'Try refreshing the table and search again. The query was not saved in the session.'), 400
    
    Table = mdl.get_model_by_tablename(db_tablename)
    orm_sql = db.select(Table).from_statement(text(query))

    for obj in db.session.execute(orm_sql).scalars():
        print(obj)
        obj.is_deprecated = not obj.is_deprecated #works even for null cases :)
        obj.deprecated_on = now_utc() #have it be a date, could be use to look at recently deprecated items to undepricate
        obj.deprecated_by = current_user
    db.session.commit()
    return '', 204
    

application/tables/templates/component_table.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" type= "text/css" href="{{ url_for('tables.static', filename='styles/tables.css') }}">
<link rel="stylesheet" type= "text/css" href="{{ url_for('parts.static', filename='styles/module_table.css') }}">
<script src="{{ url_for('tables.static', filename='js/table.js') }}"></script>

<h1 class="ms-2 mb-0">Components Inventory</h1>
<p class="ms-2 mb-0"> All the parts that will be used to construct Modules and Super-Modules: Module PCBs, ETROCs, LGADs, ETROC+LGAD Subassemblies and Readout Boards.</p>

<!-- html for viewing table -->
<div id="grid-table" class="ms-3 me-3"></div>

<script>
    console.log(JSON.stringify($("#test-tabler")));
    const editableCellAttributes = (data, row, col) => {
        if (row) {
            return {contentEditable: 'true', 'data-element-id': row.cells[0].data};
        }
        else {
            return {};
        }
    };
    const cellClickRedirect = (cell, row, column) => {
        if (cell) {
            return {
                'style': 'cursor: pointer',
                'onclick': function(event) {
                    window.location.href = `/parts/component/${row.cells[2].data}`;
                }
            }
        }
    };

    // const metadata_formatter = (cell, row) => {
    //     const metadata = JSON.parse(cell);
    //     let table = `
    //     <table class="table-secondary">

    //     <tbody>`;
    //     let index = 1;
    //     for (const key in metadata) {
    //         if (metadata.hasOwnProperty(key)) {
    //             table += `
    //         <tr>
    //         <th scope="row">${index}</th>
    //         <td>${key}</td>
    //         <td>${metadata[key]}</td>
    //         </tr>`;
    //             index++;
    //         }
    //     }
    //     table += `
    //         </tbody>
    //     </table>`;
    //     return gridjs.h('div', {
    //         onClick: () => alert('Edit Metadata')
    //     }, gridjs.html(table));
    // }

    var not_allowed_color = '#FFE3E3';
    var pointer_color = '#D4EAFF';
    
    columns = [
        { id: 'id',               name: 'ID',               'attributes': cellClickRedirect},
        { id: 'username',         name: 'Username',         'attributes': cellClickRedirect},
        { id: 'component_sn',     name:  'Serial Number',   'attributes': cellClickRedirect},
        { id: 'component_type',   name: 'Component Type',   'attributes': cellClickRedirect},
        { id: 'parent_sn',        name: 'Parent Component', 'attributes': cellClickRedirect},
        { id: 'subcomponents',    name: 'Subcomponents',    'attributes': cellClickRedirect},
        { id: 'module_sn',        name: 'Module',           'attributes': cellClickRedirect},
        { id: 'current_location', name: 'Location',         'attributes': cellClickRedirect},
        { id: 'meta_data',        name: 'Metadata',         'attributes': editableCellAttributes},
        { id: 'created_at',       name: 'Created At',       'attributes': cellClickRedirect},
    ]

    let search_keywords = ['MOD', 'COMP', 'LOC', 'COMPTYPE', 'DEPRECATED', 'ID', 'METADATA', 'ASSEMBLY_EXISTS', 'TEST_EXISTS']

    const table = Table(
        'grid-table',
        columns, 
        "{{ url_for('tables.table_data', db_tablename=db_tablename) }}",
        "{{ url_for('tables.depricate', db_tablename=db_tablename) }}",
        1000,
        search_keywords
    )

    let savedValue;

    $("#grid-table").on('focusin', ev => {
        if (ev.target.tagName === 'TD') {
            savedValue = ev.target.textContent;
        }
    });

    $("#grid-table").on('focusout', ev => {
        if (ev.target.tagName === 'TD') {
            if (savedValue !== ev.target.textContent) {
                $.ajax({
                    url: "{{ url_for('tables.update', db_tablename=db_tablename) }}",
                    type: 'POST',
                    contentType: "application/json; charset=utf-8",
                    dataType: 'json',
                    data: JSON.stringify({
                        id: ev.target.dataset.elementId,
                        [ev.target.dataset.columnId]: ev.target.textContent
                    }),
                    success: (result) => {
                        $("#ajax-flashes").append(`
                            <div class="alert alert-success alert-dismissible fade show" role="alert"> 
                                "Successfully updated!"
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        `);
                    },
                    error: (result) => {
                        var error = result?.responseJSON?.message;
                        $("#ajax-flashes").append(`
                            <div class="alert alert-danger alert-dismissible fade show" role="alert"> 
                                ${error}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        `);
                    }
                });
            }
            savedValue = undefined;
        }
    });

    $("#grid-table").on('keydown', ev => {
    if (ev.target.tagName === 'TD') {
        if (ev.key === 'Escape') {
        ev.target.textContent = savedValue;
        ev.target.blur();
        }
        else if (ev.key === 'Enter') {
        ev.preventDefault();
        ev.target.blur();
        }
    }
    });

</script>


{% endblock %}

application/tables/templates/construction_table.html
{% extends "base.html" %}
{% block content %}
<link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />
<link rel="stylesheet" type= "text/css" href="{{ url_for('tables.static', filename='styles/tables.css') }}">
<script src="{{ url_for('tables.static', filename='js/table.js') }}"></script>

<h1 class="text-center">{% if constr_table == 'test'%}Tests{%else%}Assemblies{%endif%}</h1>
<!-- html for viewing table -->
<div id="table" class="ms-3 me-3"></div>

<script>
    columns = [
            { id: 'id', name: "ID"},
            { id: 'username', name: 'Username'},
            { id: 'module_type', name: 'Module Type'},
            { id: 'module_sn', name:  'Module SN'},
            { id: 'component_type', name: 'Component Type'},
            { id: 'component_sn', name: 'Component SN'},
            { id: 'component_pos', name: 'Component Pos'},
            { id: 'type', name: 'Type of table'},
            { id: 'location', name: 'Location'},
            { id: 'measurement_date', name: 'Measurement Date'},
        ]

    let search_keywords = [
        'ID','MOD','COMP', 
        '{% if constr_table == "assembly" %}ASSEMBLY{% elif constr_table == "test" %}TEST{%endif%}', 
        'DEPRECATED', 'DATA']

    const table = Table(
        'table',
        columns, 
        "{{ url_for('tables.table_data', db_tablename=constr_table) }}",
        "{{ url_for('tables.depricate', db_tablename=constr_table) }}",
        1000,
        search_keywords
    )
    table.on('rowClick', (...args) => window.location.href = "/construction/{{constr_table}}/" + JSON.stringify(args[1]["_cells"][0]["data"]));

</script>

{% endblock %}

application/tables/templates/module_table.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" type= "text/css" href="{{ url_for('tables.static', filename='styles/tables.css') }}">
<link rel="stylesheet" type= "text/css" href="{{ url_for('parts.static', filename='styles/module_table.css') }}">
<script src="{{ url_for('tables.static', filename='js/table.js') }}"></script>

<h1>Module Summary</h1>
<h3>Select Module</h3>

<!-- html for viewing table -->
<div id="grid-table" class="ms-3 me-3"></div>

<script>
    columns = [
        { id: 'id', name: "ID"},
        { id: 'username', name: 'Username'},
        { id: 'module_sn', name:  'Module Serial Number'},
        { id: 'module_type', name: 'Module Type'},
        { id: 'current_location', name: 'Current Location'},
        { id: 'assembly_location', name: 'Assembly Location'},
        { id: 'created_at', name: 'Created At'},
    ];
    let search_keywords = ['ID','MOD', 'LOC', 'COMP', 'MODTYPE', 'DEPRECATED', 'ASSEMBLY_LOC','ASSEMBLY_EXISTS', 'TEST_EXISTS']

    const table = Table(
        'grid-table',
        columns, 
        "{{ url_for('tables.table_data', db_tablename=db_tablename) }}",
        "{{ url_for('tables.depricate', db_tablename=db_tablename) }}",
        1000,
        search_keywords
    ).render(document.getElementById('grid-table'));
    table.on('rowClick', (...args) => window.location.href = "/parts/module/" + JSON.stringify(args[1]["_cells"][2]["data"]).slice(1,-1));
</script>


{% endblock %}

application/tables/templates/shipment_table.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" type= "text/css" href="{{ url_for('tables.static', filename='styles/tables.css') }}">
<script src="{{ url_for('tables.static', filename='js/table.js') }}"></script>

<div class="shipment-page">
    <h1>View Shipments</h1>
    <small class="text-muted">Clear the search bar to see all the shipments. To mark a shipment as received and/or edit/verify it, click on the row. </small>
</div>
<div id="grid-table" class="ms-3 me-3"></div>

<script>
    columns = [
        { id: 'id', name: 'Shipment Number'},
        { id: 'username', name: 'Username'},
        { id: 'origin', name: 'Origin'},
        { id: 'destination', name: 'Destination'},
        { id: 'shipment_date', name: 'Shipment Date'},
        { id: 'reception_date', name: 'Reception Date'},
        { id: 'parts', name: 'Parts', formatter: (cell) => {
            return gridjs.html(cell)
            }
        },
        { id: 'tracking_number', name: 'Tracking Number'},
        { id: 'is_recieved', name: 'Is Received'},
    ];

    let search_keywords = [
        'ID','ORIGIN', 'DEST', 'TRACKNUM', 'TRANSIT', 'MOD', 'MODTYPE', 'COMP', 'COMPTYPE', 'DEPRECATED', 'TRANSIT'
    ]
                       
    const table = Table(
        'grid-table',
        columns, 
        "{{ url_for('tables.table_data', db_tablename=db_tablename) }}",
        "{{ url_for('tables.depricate', db_tablename=db_tablename) }}",
        1000,
        search_keywords
    );
    table.on('rowClick', (...args) => window.location.href = "/shipments/verify-shipment/" + JSON.stringify(args[1]["_cells"][0]["data"]));
</script>

{% endblock %}